<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2AFDCIK" failures="10" tests="13" name="Trigonometry Tests" time="0.004" errors="0" timestamp="26 июн. 2018 16:37:17 GMT">
  <testcase classname="SinCalcTestDouble" name="sinTest" time="0.0"/>
  <testcase classname="SinCalcTestDouble" name="sinTest" time="0.0"/>
  <testcase classname="SinCalcTestDouble" name="sinTest" time="0.0"/>
  <testcase classname="CosCalcTestDouble" name="sinTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Cos operation is incorrect: Cos 0.0 = 0.0 expected [1.0] but found [0.0]">
      <![CDATA[java.lang.AssertionError: Cos operation is incorrect: Cos 0.0 = 0.0 expected [1.0] but found [0.0]
at CosCalcTestDouble.sinTest(CosCalcTestDouble.java:12)
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:24)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- sinTest -->
  <testcase classname="CosCalcTestDouble" name="sinTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Cos operation is incorrect: Cos 1.0 = 0.8414709848078965 expected [0.5143952585235492] but found [0.8414709848078965]">
      <![CDATA[java.lang.AssertionError: Cos operation is incorrect: Cos 1.0 = 0.8414709848078965 expected [0.5143952585235492] but found [0.8414709848078965]
at CosCalcTestDouble.sinTest(CosCalcTestDouble.java:12)
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:24)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- sinTest -->
  <testcase classname="CosCalcTestDouble" name="sinTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Cos operation is incorrect: Cos -1.0 = -0.8414709848078965 expected [0.5143952585235492] but found [-0.8414709848078965]">
      <![CDATA[java.lang.AssertionError: Cos operation is incorrect: Cos -1.0 = -0.8414709848078965 expected [0.5143952585235492] but found [-0.8414709848078965]
at CosCalcTestDouble.sinTest(CosCalcTestDouble.java:12)
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:24)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- sinTest -->
  <testcase classname="TgCalcTestDouble" name="tgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Tg operation is incorrect: Tg 0.0 = NaN expected [0.0] but found [NaN]">
      <![CDATA[java.lang.AssertionError: Tg operation is incorrect: Tg 0.0 = NaN expected [0.0] but found [NaN]
at TgCalcTestDouble.tgTest(TgCalcTestDouble.java:13)
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:24)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- tgTest -->
  <testcase classname="TgCalcTestDouble" name="tgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Tg operation is incorrect: Tg 1.0 = 1.0 expected [1.5574077246549] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Tg operation is incorrect: Tg 1.0 = 1.0 expected [1.5574077246549] but found [1.0]
at TgCalcTestDouble.tgTest(TgCalcTestDouble.java:13)
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:24)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- tgTest -->
  <testcase classname="TgCalcTestDouble" name="tgTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Tg operation is incorrect: Tg -10.0 = 1.0 expected [-0.64836082745909] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Tg operation is incorrect: Tg -10.0 = 1.0 expected [-0.64836082745909] but found [1.0]
at TgCalcTestDouble.tgTest(TgCalcTestDouble.java:13)
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:24)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- tgTest -->
  <testcase classname="TgCalcTestDouble" name="tgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Tg operation is incorrect: Tg 10.0 = 1.0 expected [0.6483608274590866] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Tg operation is incorrect: Tg 10.0 = 1.0 expected [0.6483608274590866] but found [1.0]
at TgCalcTestDouble.tgTest(TgCalcTestDouble.java:13)
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:24)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- tgTest -->
  <testcase classname="CtgCalcTestDouble" name="ctgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Ctg operation is incorrect: Ctg 1.0 = 0.7615941559557649 expected [0.64209261593433] but found [0.7615941559557649]">
      <![CDATA[java.lang.AssertionError: Ctg operation is incorrect: Ctg 1.0 = 0.7615941559557649 expected [0.64209261593433] but found [0.7615941559557649]
at CtgCalcTestDouble.ctgTest(CtgCalcTestDouble.java:14)
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:24)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- ctgTest -->
  <testcase classname="CtgCalcTestDouble" name="ctgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Ctg operation is incorrect: Ctg -10.0 = -0.9999999958776927 expected [-1.5423510453569] but found [-0.9999999958776927]">
      <![CDATA[java.lang.AssertionError: Ctg operation is incorrect: Ctg -10.0 = -0.9999999958776927 expected [-1.5423510453569] but found [-0.9999999958776927]
at CtgCalcTestDouble.ctgTest(CtgCalcTestDouble.java:14)
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:24)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- ctgTest -->
  <testcase classname="CtgCalcTestDouble" name="ctgTestNegative" time="0.0">
    <failure type="org.testng.TestException" message="
Method CtgCalcTestDouble.ctgTestNegative()[pri:0, instance:CtgCalcTestDouble@4f209819] should have thrown an exception of type class org.junit.rules.ExpectedException">
      <![CDATA[org.testng.TestException: 
Method CtgCalcTestDouble.ctgTestNegative()[pri:0, instance:CtgCalcTestDouble@4f209819] should have thrown an exception of type class org.junit.rules.ExpectedException
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:24)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- ctgTestNegative -->
</testsuite> <!-- Trigonometry Tests -->
