<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2AFDCIK" failures="0" tests="4" name="SqrtCalcTestDouble" time="0.000" errors="1" timestamp="28 июн. 2018 16:05:34 GMT" skipped="0">
  <testcase classname="SqrtCalcTestDouble" name="sqrtTest" time="0.000"/>
  <testcase classname="SqrtCalcTestDouble" name="sqrtTest" time="0.000"/>
  <testcase classname="SqrtCalcTestDouble" name="sqrtTest" time="0.000">
    <error message="
Method SqrtCalcTestDouble.sqrtTest()[pri:0, instance:SqrtCalcTestDouble@34f22f9d] should have thrown an exception of type class java.lang.Exception" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method SqrtCalcTestDouble.sqrtTest()[pri:0, instance:SqrtCalcTestDouble@34f22f9d] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1140)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:27)
]]>
    </error>
  </testcase> <!-- sqrtTest -->
  <testcase classname="SqrtCalcTestDouble" name="sqrtTest" time="0.000"/>
</testsuite> <!-- SqrtCalcTestDouble -->
