<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2AFDCIK" failures="2" tests="3" name="com.epam.cdp.calc_unit_tests.tests.MultCalcTestDouble" time="0.001" errors="0" timestamp="04 июл. 2018 18:22:09 GMT" skipped="0">
  <testcase classname="com.epam.cdp.calc_unit_tests.tests.MultCalcTestDouble" name="multTest" time="0.000">
    <failure message="Mult operation is incorrect: -1.11 * 1.11 = -2.0 expected [-1.2321] but found [-2.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Mult operation is incorrect: -1.11 * 1.11 = -2.0 expected [-1.2321] but found [-2.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.epam.cdp.calc_unit_tests.tests.MultCalcTestDouble.multTest(MultCalcTestDouble.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </failure>
  </testcase> <!-- multTest -->
  <testcase classname="com.epam.cdp.calc_unit_tests.tests.MultCalcTestDouble" name="multTest" time="0.001">
    <failure message="Mult operation is incorrect: 1.11 * 1.11 = 1.0 expected [1.2321] but found [1.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Mult operation is incorrect: 1.11 * 1.11 = 1.0 expected [1.2321] but found [1.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.epam.cdp.calc_unit_tests.tests.MultCalcTestDouble.multTest(MultCalcTestDouble.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </failure>
  </testcase> <!-- multTest -->
  <testcase classname="com.epam.cdp.calc_unit_tests.tests.MultCalcTestDouble" name="multTest" time="0.000"/>
</testsuite> <!-- com.epam.cdp.calc_unit_tests.tests.MultCalcTestDouble -->
