<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2AFDCIK" failures="1" tests="4" name="Sqrt Tests" time="0.005" errors="0" timestamp="04 июл. 2018 18:22:09 GMT">
  <testcase classname="com.epam.cdp.calc_unit_tests.tests.SqrtCalcTestDouble" name="sqrtTest" time="0.0">
    <failure type="org.testng.TestException" message="
Method SqrtCalcTestDouble.sqrtTest()[pri:0, instance:com.epam.cdp.calc_unit_tests.tests.SqrtCalcTestDouble@4ce1d6d0] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method SqrtCalcTestDouble.sqrtTest()[pri:0, instance:com.epam.cdp.calc_unit_tests.tests.SqrtCalcTestDouble@4ce1d6d0] should have thrown an exception of type class java.lang.Exception
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:31)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sqrtTest -->
  <testcase classname="com.epam.cdp.calc_unit_tests.tests.SqrtCalcTestDouble" name="sqrtTest" time="0.003"/>
  <testcase classname="com.epam.cdp.calc_unit_tests.tests.SqrtCalcTestDouble" name="sqrtTest" time="0.0"/>
  <testcase classname="com.epam.cdp.calc_unit_tests.tests.SqrtCalcTestDouble" name="sqrtTest" time="0.001"/>
</testsuite> <!-- Sqrt Tests -->
